/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as IaRouteImport } from './routes/ia'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as Verificar2faRouteImport } from './routes/verificar-2fa'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as AutomacoesBuilderRouteImport } from './routes/automacoes_.builder'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as ConfiguracoesPapeisRouteImport } from './routes/configuracoes.papeis'
import { Route as WhatsappTemplatesRouteImport } from './routes/whatsapp_.templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const Verificar2faRoute = Verificar2faRouteImport.update({
  id: '/verificar-2fa',
  path: '/verificar-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesBuilderRoute = AutomacoesBuilderRouteImport.update({
  id: '/automacoes_/builder',
  path: '/automacoes/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientesRoute,
} as any)
const ConfiguracoesPapeisRoute = ConfiguracoesPapeisRouteImport.update({
  id: '/papeis',
  path: '/papeis',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const WhatsappTemplatesRoute = WhatsappTemplatesRouteImport.update({
  id: '/whatsapp_/templates',
  path: '/whatsapp/templates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automacoes': typeof AutomacoesRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/crm': typeof CrmRoute
  '/ia': typeof IaRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/verificar-2fa': typeof Verificar2faRoute
  '/whatsapp': typeof WhatsappRoute
  '/automacoes/builder': typeof AutomacoesBuilderRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/configuracoes/papeis': typeof ConfiguracoesPapeisRoute
  '/whatsapp/templates': typeof WhatsappTemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automacoes': typeof AutomacoesRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/crm': typeof CrmRoute
  '/ia': typeof IaRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/verificar-2fa': typeof Verificar2faRoute
  '/whatsapp': typeof WhatsappRoute
  '/automacoes/builder': typeof AutomacoesBuilderRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/configuracoes/papeis': typeof ConfiguracoesPapeisRoute
  '/whatsapp/templates': typeof WhatsappTemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automacoes': typeof AutomacoesRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/crm': typeof CrmRoute
  '/ia': typeof IaRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/verificar-2fa': typeof Verificar2faRoute
  '/whatsapp': typeof WhatsappRoute
  '/automacoes_/builder': typeof AutomacoesBuilderRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/configuracoes/papeis': typeof ConfiguracoesPapeisRoute
  '/whatsapp_/templates': typeof WhatsappTemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automacoes'
    | '/cadastro'
    | '/clientes'
    | '/configuracoes'
    | '/crm'
    | '/ia'
    | '/login'
    | '/recuperar-senha'
    | '/relatorios'
    | '/verificar-2fa'
    | '/whatsapp'
    | '/automacoes/builder'
    | '/clientes/$id'
    | '/configuracoes/papeis'
    | '/whatsapp/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automacoes'
    | '/cadastro'
    | '/clientes'
    | '/configuracoes'
    | '/crm'
    | '/ia'
    | '/login'
    | '/recuperar-senha'
    | '/relatorios'
    | '/verificar-2fa'
    | '/whatsapp'
    | '/automacoes/builder'
    | '/clientes/$id'
    | '/configuracoes/papeis'
    | '/whatsapp/templates'
  id:
    | '__root__'
    | '/'
    | '/automacoes'
    | '/cadastro'
    | '/clientes'
    | '/configuracoes'
    | '/crm'
    | '/ia'
    | '/login'
    | '/recuperar-senha'
    | '/relatorios'
    | '/verificar-2fa'
    | '/whatsapp'
    | '/automacoes_/builder'
    | '/clientes/$id'
    | '/configuracoes/papeis'
    | '/whatsapp_/templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomacoesRoute: typeof AutomacoesRoute
  CadastroRoute: typeof CadastroRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  CrmRoute: typeof CrmRoute
  IaRoute: typeof IaRoute
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  Verificar2faRoute: typeof Verificar2faRoute
  WhatsappRoute: typeof WhatsappRoute
  AutomacoesBuilderRoute: typeof AutomacoesBuilderRoute
  WhatsappTemplatesRoute: typeof WhatsappTemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificar-2fa': {
      id: '/verificar-2fa'
      path: '/verificar-2fa'
      fullPath: '/verificar-2fa'
      preLoaderRoute: typeof Verificar2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes_/builder': {
      id: '/automacoes_/builder'
      path: '/automacoes/builder'
      fullPath: '/automacoes/builder'
      preLoaderRoute: typeof AutomacoesBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/configuracoes/papeis': {
      id: '/configuracoes/papeis'
      path: '/papeis'
      fullPath: '/configuracoes/papeis'
      preLoaderRoute: typeof ConfiguracoesPapeisRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/whatsapp_/templates': {
      id: '/whatsapp_/templates'
      path: '/whatsapp/templates'
      fullPath: '/whatsapp/templates'
      preLoaderRoute: typeof WhatsappTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientesRouteChildren {
  ClientesIdRoute: typeof ClientesIdRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesIdRoute: ClientesIdRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

interface ConfiguracoesRouteChildren {
  ConfiguracoesPapeisRoute: typeof ConfiguracoesPapeisRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesPapeisRoute: ConfiguracoesPapeisRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomacoesRoute: AutomacoesRoute,
  CadastroRoute: CadastroRoute,
  ClientesRoute: ClientesRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  CrmRoute: CrmRoute,
  IaRoute: IaRoute,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RelatoriosRoute: RelatoriosRoute,
  Verificar2faRoute: Verificar2faRoute,
  WhatsappRoute: WhatsappRoute,
  AutomacoesBuilderRoute: AutomacoesBuilderRoute,
  WhatsappTemplatesRoute: WhatsappTemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
